## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [13]:
import torch
import torch.nn as nn
from collections import OrderedDict
from sklearn.metrics import accuracy_score


In [38]:
# your code here
#model1 = nn.Sequential(OrderedDict([
#    ('hidden', nn.
#]))


class Network1(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super(Network1, self).__init__()
        self.model_stack = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 5)), 
    ('la1', nn.ReLU()),
    ('hidden2', nn.Linear(5, 2)),
    ('la2', nn.Sigmoid())
]))
    def forward(self, x):
        x = self.model_stack(x)
        return x


class Network2(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super(Network2, self).__init__()
        self.model_stack = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 5)), 
    ('la1', nn.LeakyReLU()),
    ('hidden2', nn.Linear(5, 2)),
    ('la2', nn.Sigmoid())
]))
    def forward(self, x):
        x = self.model_stack(x)
        return x
    
    
class Network3(torch.nn.Module):
    def __init__(self, input_dim, output_dim):
        super(Network3, self).__init__()
        self.model_stack = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 100)), 
    ('la1', nn.ReLU()),
    ('hidden2', nn.Linear(100, 2)),
    ('la3', nn.Sigmoid())
]))
    def forward(self, x):
        x = self.model_stack(x)
        return x
            
model1 = Network1(None, None)
model2 = Network2(None, None)
model3 = Network3(None, None)


In [ ]:
print(model1)

In [39]:
# your code here
#data_in = torch.tensor( ...
data_in = torch.tensor([[0,0],
                       [0,1],
                       [0,1],
                        [1,0]]
                      ).float()
print(data_in)

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [40]:
# your code here
# data_target = torch.tensor( ...
data_target = torch.tensor([[0,0],
                          [0,1],
                          [0,1],
                          [1,0]]).float()
print(data_target)

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])


In [41]:
# your code here
criterion = nn.MSELoss()  
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)
optimizer2 = torch.optim.SGD(model2.parameters(), lr=0.1)
optimizer3 = torch.optim.SGD(model3.parameters(), lr=0.1)

In [42]:
# your code here
# Train model 1
import numpy as np

num_epochs = 10000
for epoch in range(num_epochs):
    outputs = model1(data_in)
    accuracy = accuracy_score(outputs.detach().round(), data_target.detach().round())
    if accuracy == 1:
        print(f'Accuracy 1 after {epoch} epochs')
        break;
        
    loss = criterion(outputs, data_target)
    
    optimizer1.zero_grad()
    loss.backward()
    optimizer1.step()

    if (epoch + 1) % 1000 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item()}')

Accuracy 1 after 59 epochs


In [43]:
#train model 2
num_epochs = 10000
for epoch in range(num_epochs):
    outputs = model2(data_in)
    accuracy = accuracy_score(outputs.detach().round(), data_target.detach().round())
    if accuracy == 1:
        print(f'Accuracy 1 after {epoch} epochs')
        break;
        
    loss = criterion(outputs, data_target)

    optimizer2.zero_grad()
    loss.backward()
    optimizer2.step()

    if (epoch + 1) % 1000 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item()}')

Accuracy 1 after 976 epochs


In [44]:
#train model 3
num_epochs = 10000
for epoch in range(num_epochs):
    outputs = model3(data_in)
    accuracy = accuracy_score(outputs.detach().round(), data_target.detach().round())
    if accuracy == 1:
        print(f'Accuracy 1 after {epoch} epochs')
        break;
        
    loss = criterion(outputs, data_target)

    optimizer3.zero_grad()
    loss.backward()
    optimizer3.step()

    if (epoch + 1) % 1000 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item()}')

Accuracy 1 after 15 epochs


In [45]:
# your code here
# visualize the resuts
print(data_in)
print(model1(data_in))
print(model2(data_in))
print(model3(data_in))

tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
tensor([[0.4175, 0.4997],
        [0.4130, 0.5272],
        [0.4130, 0.5272],
        [0.5035, 0.4178]], grad_fn=<SigmoidBackward0>)
tensor([[0.3644, 0.2535],
        [0.0334, 0.9256],
        [0.0334, 0.9256],
        [0.5001, 0.1428]], grad_fn=<SigmoidBackward0>)
tensor([[0.3943, 0.4995],
        [0.2652, 0.6017],
        [0.2652, 0.6017],
        [0.5052, 0.4781]], grad_fn=<SigmoidBackward0>)


In [154]:
# your code here
# print model weights
for param in model1.parameters():
    print(param)
for param in model2.parameters():
    print(param)
for param in model3.parameters():
    print(param)

Parameter containing:
tensor([[-0.8885,  2.0234],
        [ 1.9998, -1.5329],
        [ 1.4750, -0.5849],
        [-0.0865, -0.4637],
        [-2.1092, -2.1093],
        [-1.6608, -0.0469],
        [ 1.8237,  0.7522],
        [-1.4053,  2.2837],
        [-0.8191,  1.9239],
        [-1.4352,  1.4568]], requires_grad=True)
Parameter containing:
tensor([ 0.2145,  1.5329,  0.2308, -0.3576,  2.1092,  1.9102, -0.0106,  1.0019,
         0.0591,  0.9581], requires_grad=True)
Parameter containing:
tensor([[-1.6874,  1.5971,  1.5327, -0.2292, -2.3077, -1.7325,  1.5409, -1.6851,
         -0.9558, -1.8339],
        [ 1.9401, -2.1650, -0.8163,  0.3100, -1.8366, -1.5012, -0.0245,  1.3867,
          2.1957,  0.7104]], requires_grad=True)
Parameter containing:
tensor([-0.6806, -1.9704], requires_grad=True)
Parameter containing:
tensor([[ 2.2479, -2.7492],
        [-3.0371,  2.4990],
        [ 3.5265, -0.2488],
        [ 2.3959, -3.4450],
        [ 3.1163, -0.3567]], requires_grad=True)
Parameter conta